"""
Streaming chat logic for llama.cpp provider.

Handles SSE response parsing, content/thinking buffering, tool call accumulation,
and WebSocket message sending with configurable flush thresholds.

TOKEN STATISTICS (Bulletproof Per-Request):
    The chat_stream() function now captures REAL token counts from llama.cpp's
    final SSE response chunk via the 'usage' field:
        - prompt_tokens:    Actual tokens sent as input/context
        - completion_tokens: Actual tokens generated by the model
        - eval_duration:     Time spent generating (nanoseconds)

    These are packaged into a TokenStats dataclass and returned alongside
    the response string. This eliminates the old module-level global approach
    which was broken for concurrent users.

    Return value is now a tuple: (response_str, TokenStats)

THINKING / REASONING MODE:
    When enable_thinking=True and the server supports reasoning (--reasoning on),
    llama.cpp emits 'reasoning_content' in delta chunks. This content is buffered
    and streamed to the UI as {type: "thinking"} WebSocket messages, displayed
    in a collapsible "Reasoning" block before the final answer.

HTTP CLIENT POOL:
    Uses shared httpx.AsyncClient from http_client module instead of creating
    new clients per request. Connection pooling reuses TCP connections and TLS
    sessions across all requests.
"""
import json
import os
import time
import asyncio
import logging
from typing import List, Dict, Any, Optional, Tuple

import httpx

from config import (
    CONTEXT_WINDOW_TOKENS,
    LLAMA_MIN_SAFE_MAX_TOKENS,
    STREAM_BUFFER_SIZE_CHARS,
    STREAM_BUFFER_SIZE_MSGS,
    STREAM_BUFFER_TIMEOUT_SEC,
    LLAMA_SERVER_MAX_NEW_TOKENS,
    LLAMA_STREAM_STALL_TIMEOUT_SEC,
    LLAMA_AUTO_RESTART_ON_STALL,
    LLAMA_MODEL_STATE_TTL_SEC,
)

from ..token_stats import TokenStats
from .converter import convert_messages_for_vision
from .payload import build_llama_payload
from .model_utils import _is_mmproj_file, normalize_model_name
from .vision_support import VisionNotAvailableError, make_vision_error, _looks_like_mmproj_error
from .http_client import get_async_client
from . import model_state

logger = logging.getLogger("COOLEMS.Provider.Llama.Streaming")


async def _iter_sse_with_stall(aiter, timeout_sec: int, conv_id: str, api_url: str):
    """Wrap the SSE line iterator with a per-chunk silence watchdog.

    b10441 hang fix: if llama-server accepts the request but then sends no
    chunks at all (GPU idle / pipe deadlock / frozen decode loop), the old code
    waited forever with zero logs. This wrapper raises after `timeout_sec` of
    silence so the caller fails fast, and optionally auto-restarts the server.

    Yields SSE lines exactly as aiter_lines() would.
    """
    chunks = 0
    while True:
        t0 = time.time()
        try:
            item = await asyncio.wait_for(aiter.__anext__(), timeout=timeout_sec)
        except StopAsyncIteration:
            return
        except (TimeoutError, asyncio.TimeoutError):
            logger.error(
                f"[STREAM-STALL] llama-server sent NO SSE chunk for {timeout_sec}s "
                f"(chunks so far: {chunks}, conv={conv_id}). GPU idle / server frozen - aborting request."
            )
            restarted = False
            if LLAMA_AUTO_RESTART_ON_STALL:
                logger.error("[STREAM-STALL] Auto-restart enabled - killing llama-server and restarting...")
                try:
                    from .server import (
                        _kill_orphaned_process,
                        _kill_llama_server_by_port,
                        wait_for_port_free_async,
                        start_server as _restart,
                    )
                    from config import LLAMA_SERVER_PORT

                    # (2026-09 threadless fix): the old run_in_executor(_do_restart) wrapper is GONE.
                    # The server functions are async now - awaiting them on THIS loop keeps heartbeats
                    # and other clients responsive during the restart; only the two true OS leaves
                    # (terminate/wait, netstat/taskkill port cleanup) go through asyncio.to_thread,
                    # exactly like reload_with_model() does it. The old code also imported a removed
                    # name (wait_for_port_free), so this path raised ImportError on first stall.
                    await asyncio.to_thread(_kill_orphaned_process)
                    await asyncio.to_thread(_kill_llama_server_by_port, LLAMA_SERVER_PORT)
                    if await wait_for_port_free_async(LLAMA_SERVER_PORT):
                        restarted = await _restart(api_url)
                except Exception as restart_err:
                    logger.error(f"[STREAM-STALL] Auto-restart failed: {restart_err}")
            raise RuntimeError(
                f"llama.cpp stream stalled: no SSE chunk for {timeout_sec}s after {chunks} chunk(s). "
                f"Server auto-restarted={restarted}"
            )

        elapsed = time.time() - t0
        if chunks == 0:
            logger.info(f"[STREAM] First SSE chunk received after {elapsed:.2f}s (conv={conv_id})")
        elif elapsed > 15:
            logger.warning(f"[STREAM] Slow gap between chunks: {elapsed:.1f}s (chunk #{chunks}, conv={conv_id})")
        chunks += 1

        try:
            yield item
        except GeneratorExit:
            # Consumer stopped reading (stop_event / break) - close quietly
            return


async def chat_stream(
    api_url: str,
    timeout: int,
    model: str,
    messages: List[Dict],
    websocket: Any,
    temperature: float = 0.7,
    enable_thinking: bool = False,
    conv_id: Optional[str] = None,
    tools: Optional[list] = None,
    stop_event: Optional[asyncio.Event] = None,
) -> Tuple[str, TokenStats]:
    """
    Stream chat completions from llama.cpp via SSE.

    Captures REAL token counts from llama.cpp's final response chunk and returns
    them in a TokenStats dataclass. This is bulletproof for concurrent users
    because each call gets its own TokenStats — no shared globals.

    Args:
        api_url: llama.cpp API base URL (e.g. http://localhost:5000).
        timeout: HTTP timeout in seconds.
        model: Model name to use.
        messages: List of message dicts with 'role' and 'content'.
        websocket: FastAPI WebSocket for streaming content chunks.
        temperature: Sampling temperature (default 0.7).
        enable_thinking: Whether to enable thinking/reasoning mode. When True,
                         reasoning_content from delta chunks is streamed as
                         {type: "thinking"} messages to the UI.
        conv_id: Conversation ID for logging and stop control.
        tools: Optional list of tool definitions for native tool calling.
        stop_event: asyncio.Event set by the stop endpoint when user clicks
                   the red stop button. Checked on every SSE chunk to abort
                   generation immediately.

    Returns:
        Tuple of (response_string, TokenStats).
        - response_string: Either plain text or JSON string with tool_calls.
        - TokenStats: Real token counts from llama.cpp including prompt_tokens,
          completion_tokens, eval_duration, and calculated speed.

    Raises:
        ConnectionError: If llama.cpp service is not running.
        TimeoutError: If the request times out.
        FileNotFoundError: If the model is not found.
        RuntimeError: If llama.cpp returns an error.
    """

    # Convert messages to OpenAI-compatible multimodal format
    messages = convert_messages_for_vision(messages)

    logger.info(f"Sending {len(messages)} message(s) to llama.cpp")

    # Log if images are present
    for msg in messages:
        content = msg.get("content", "")
        if isinstance(content, list):
            image_count = sum(1 for c in content if isinstance(c, dict) and c.get("type") == "image_url")
            if image_count:
                logger.info(f"Message contains {image_count} image(s) for vision processing")

    full_response_parts = []
    content_buffer = ""
    think_buffer = ""
    message_counter = 0
    last_send_time = asyncio.get_running_loop().time()

    # Accumulator for tool_calls deltas (llama.cpp streams tool calls as deltas)
    accumulated_tool_calls = []

    # Variables to capture from the final SSE chunk
    prompt_tokens: int = 0
    completion_tokens: int = 0
    eval_duration_seconds: float = 0.0
    finish_reason: Optional[str] = None   # "stop" | "length" - set by llama.cpp on the last chunk

    # Track if generation was stopped by user
    was_stopped = False

    async def flush_content():
        """Flush the content buffer to the WebSocket client."""
        nonlocal content_buffer, message_counter, last_send_time
        if content_buffer and websocket:
            try:
                await websocket.send_text(json.dumps({
                    "type": "content",
                    "content": content_buffer
                }))
                content_buffer = ""
                message_counter = 0
                last_send_time = asyncio.get_running_loop().time()
            except Exception as e:
                logger.warning(f"Failed to send content buffer: {e}")
                raise

    async def flush_thinking():
        """Flush the thinking buffer to the WebSocket client."""
        nonlocal think_buffer
        if think_buffer and websocket:
            try:
                await websocket.send_text(json.dumps({
                    "type": "thinking",
                    "content": think_buffer
                }))
                think_buffer = ""
            except Exception as e:
                logger.warning(f"Failed to send thinking buffer: {e}")
                raise

    # ---- SAFE MAX-TOKENS (context-overflow guard) ------------------------
    # Requesting max_tokens == full context window is what caused the b10441
    # "Failed to parse tool call arguments as JSON" 500 errors: when the prompt
    # nearly fills the window, llama.cpp truncates generation mid-way through a
    # native tool-call JSON and then fails to parse its own output.
    # FIXED (2026-08): count tool_calls JSON in the prompt estimate. The old
    # content-only sum counted every assistant tool-call message (content="") as
    # 0 tokens, so this CONTEXT-GUARD clamp was blind to the fastest-growing part
    # of agentic history and could leave llama.cpp with no room for output.
    def _msg_chars(m: dict) -> int:
        # TRUNCATION-LOOP FIX (2026-09-10): the old version did len(str(content)),
        # which on a vision message counted RAW BASE64 IMAGE BLOBS as text (~330K
        # chars per 500KB image). That inflated est_prompt_tokens into the millions,
        # drove the clamp below to its floor (exactly 1024 tokens of output room),
        # cut every answer mid-sentence and made the ReAct loop re-ask forever.
        # Now: text parts count at chars/4 like before; each image is charged a
        # flat VISION estimate (llama.cpp's CLIP encoder turns a ~1600px JPEG into
        # roughly 1-2K tokens, independent of the base64 size).
        content = m.get("content", "")
        if isinstance(content, list):
            chars = 0
            for part in content:
                if not isinstance(part, dict):
                    continue
                ptype = part.get("type")
                if ptype == "text":
                    chars += len(str(part.get("text", "")))
                elif ptype == "image_url":
                    chars += _VISION_TOKENS_PER_IMAGE * 4   # flat per-image estimate
            # Ollama-style 'images' key (pre-conversion safety net) - same flat charge.
            imgs = m.get("images")
            if isinstance(imgs, list):
                chars += len(imgs) * _VISION_TOKENS_PER_IMAGE * 4
        else:
            chars = len(str(content))
        tcs = m.get("tool_calls")
        if tcs:
            try:
                chars += len(json.dumps(tcs))
            except (TypeError, ValueError):
                chars += len(str(tcs))
        return chars

    _VISION_TOKENS_PER_IMAGE = 1500   # flat estimate per attached image (see _msg_chars)
    est_prompt_tokens = sum(_msg_chars(m) for m in messages if isinstance(m, dict)) // 4
    if tools:
        try:
            est_prompt_tokens += len(json.dumps(tools)) // 4
        except Exception:
            pass
    safe_max_tokens = min(
        LLAMA_SERVER_MAX_NEW_TOKENS,
        # Floor is now configurable (was hardcoded 1024 - too small for a full
        # multi-image answer + the TASK DONE marker; see plan_20260910_1835.md).
        max(LLAMA_MIN_SAFE_MAX_TOKENS, CONTEXT_WINDOW_TOKENS - est_prompt_tokens - 512),
    )
    if safe_max_tokens < LLAMA_SERVER_MAX_NEW_TOKENS:
        logger.warning(
            f"[CONTEXT-GUARD] Prompt ~{est_prompt_tokens} tokens leaves only "
            f"{max(0, CONTEXT_WINDOW_TOKENS - est_prompt_tokens)} free of {CONTEXT_WINDOW_TOKENS}. "
            f"Clamping max_tokens to {safe_max_tokens} (default {LLAMA_SERVER_MAX_NEW_TOKENS})."
        )
    if safe_max_tokens <= LLAMA_MIN_SAFE_MAX_TOKENS:
        # The prompt alone nearly fills the window - answers WILL be short. Say so
        # loudly: this is exactly the condition that caused the 2026-09-10 truncation loop.
        logger.warning(
            f"[CONTEXT-GUARD] *** OUTPUT ROOM AT FLOOR ({safe_max_tokens} tokens) *** "
            f"prompt ~{est_prompt_tokens}/{CONTEXT_WINDOW_TOKENS}. Long answers or multi-part "
            f"responses will be truncated - consider trimming history / downscaling images."
        )

    llama_payload = build_llama_payload(
        model=model,
        messages=messages,
        stream=True,
        temperature=temperature,
        tools=tools,
        max_tokens=safe_max_tokens,
    )

    if tools:
        logger.info(f"Added {len(tools)} native tools to llama.cpp request")

    # ============================================================
    # PRE-FLIGHT HEALTH CHECK + AUTO-RESTART
    # (moved BEFORE auto-switch: the switch check below queries /v1/models,
    #  so the server must be known-up first — otherwise a downed server would
    #  silently skip the switch and request a model that is not loaded)
    # Uses shared HTTP client pool instead of creating new client per request
    # ============================================================
    try:
        http_client = await get_async_client()
        health_resp = await http_client.get(f"{api_url}/health", timeout=3.0)
        if health_resp.status_code != 200:
            raise ConnectionError("Health check failed")
    except Exception:
        logger.warning(f"[LLAMA] Server not responding - attempting auto-restart before request...")
        try:
            from .server import start_server as _start_server

            # (2026-09 threadless fix): start_server is async now - the old run_in_executor wrapper
            # passed a coroutine object to a worker thread that never awaited it, so the "restart"
            # silently did nothing while logging success. Awaiting directly keeps everything on this
            # loop; its internal blocking OS leaves already use asyncio.to_thread internally.
            restarted = await _start_server(api_url)
            if restarted:
                logger.info(f"[LLAMA] Auto-restart successful, proceeding with request")
            else:
                logger.error(f"[LLAMA] Auto-restart failed, will attempt request anyway (may fail)")
        except Exception as restart_err:
            logger.error(f"[LLAMA] Auto-restart error: {restart_err}")

    # ============================================================
    # AUTO-MODEL-SWITCH (2026-08-18 OPTIMIZED)
    # If the requested model differs from the loaded one, restart llama-server.
    #
    # Old code did a BLOCKING sync HTTP GET /v1/models on the event loop before
    # EVERY request (~1-2s latency + froze all WebSocket traffic). Now:
    #   1) Fresh in-memory state (set by server.py after every verified launch,
    #      TTL = LLAMA_MODEL_STATE_TTL_SEC) -> ZERO HTTP, microsecond compare.
    #   2) Stale/empty cache -> ONE async pooled /v1/models fetch (non-blocking).
    #   3) API unreachable -> trust the tracked state we launched ourselves.
    # Mismatch still triggers the same reload_with_model() as before.
    # ============================================================
    if _is_mmproj_file(model):
        logger.debug(f"[AUTO-SWITCH] Skipping switch - '{model}' is an mmproj file")
    else:
        try:
            req_norm = normalize_model_name(model)

            _ms_key = model_state.key_for_api_url(api_url)  # (2026-09-08 multi-chat) per-instance state
            cached_loaded, cache_fresh = model_state.get_cached_model(LLAMA_MODEL_STATE_TTL_SEC, key=_ms_key)

            if cache_fresh and normalize_model_name(cached_loaded) == req_norm:
                # Fast path: nothing changed since the last verified launch.
                logger.debug(f"[AUTO-SWITCH] Cache hit (fresh, {os.path.basename(cached_loaded)}) - no HTTP check needed")
            else:
                current_loaded = None
                if cache_fresh:
                    current_loaded = cached_loaded  # fresh but different -> switch directly
                else:
                    logger.info(f"[AUTO-SWITCH] Model state stale/empty - verifying via /v1/models once...")
                    try:
                        _http_client = await get_async_client()
                        _models_resp = await _http_client.get(f"{api_url}/v1/models", timeout=5.0)
                        if _models_resp.status_code == 200:
                            _data_list = (_models_resp.json().get("data") or [])
                            if _data_list:
                                current_loaded = _data_list[0].get("id", "") or None
                                model_state.mark_loaded(current_loaded, key=_ms_key)  # keep cache warm for next request
                    except Exception as fetch_err:
                        logger.debug(f"[AUTO-SWITCH] /v1/models verification failed ({fetch_err}) - falling back to tracked state")

                if not current_loaded and cached_loaded is not None:
                    # API unreachable (or empty): trust the model we launched ourselves.
                    current_loaded = cached_loaded
                    logger.info(f"[AUTO-SWITCH] Using tracked state fallback: '{current_loaded}'")

                if current_loaded:
                    loaded_norm = normalize_model_name(current_loaded)
                    if req_norm != loaded_norm:
                        logger.warning(
                            f"[AUTO-SWITCH] *** MODEL MISMATCH DETECTED *** "
                            f"Requesting switch from '{current_loaded}' to '{model}'"
                        )
                        # Notify user via WebSocket before switching
                        try:
                            await websocket.send_text(json.dumps({
                                "type": "system",
                                "content": f"Switching model to {model}... This may take a moment."
                            }))
                        except Exception:
                            logger.debug("WebSocket send failed during model switch notification")

                        # Run blocking reload_with_model in executor to avoid freezing event loop.
                        # Model reload kills/restarts llama-server which takes seconds-minutes.
                        # (2026-09 threadless fix): reload_with_model is async now - the old
                        # run_in_executor wrapper handed a never-awaited coroutine to a worker
                        # thread and reported "success" for a switch that never happened. Awaiting
                        # directly keeps heartbeats/UI responsive during the (up to ~120 s) reload;
                        # blocking OS leaves inside it already use asyncio.to_thread internally.
                        from .server import reload_with_model
                        success, switch_msg = await reload_with_model(api_url, model)
                        if success:
                            logger.info(f"[AUTO-SWITCH] ===== Successfully switched to {model} =====")
                        else:
                            logger.error(f"[AUTO-SWITCH] ===== FAILED to switch: {switch_msg} =====")
                    else:
                        logger.debug(f"[AUTO-SWITCH] Model already matches ('{current_loaded}') - no switch needed")
                else:
                    logger.warning("[AUTO-SWITCH] Could not determine currently loaded model (no cache, API down) - proceeding as-is")
        except Exception as auto_switch_err:
            logger.error(f"[AUTO-SWITCH] ===== ERROR in auto-switch check: {auto_switch_err} =====", exc_info=True)
    # ============================================================

    try:
        logger.info(f"Calling llama.cpp model with STREAMING: {model}")
        start_time = time.time()

        # Use shared HTTP client pool — no new client created per request
        http_client = await get_async_client()

        async with http_client.stream(
            "POST",
            f"{api_url}/v1/chat/completions",
            json=llama_payload,
            timeout=timeout,
        ) as response:
            if response.status_code == 404:
                raise FileNotFoundError(f"Model '{model}' not found in llama.cpp")
            elif response.status_code == 500:
                error_detail = await response.aread()
                err_text = error_detail.decode("utf-8", errors="replace")
                # (2026-08-23) VISION CHECK FIRST: llama-server started without a multimodal
                    # projector (mmproj) rejects ANY image input with HTTP 500 + the body
                    # "image input is not supported - hint: ... provide the mmproj". Detect it and
                    # raise a typed, human-friendly error so logs/UI never see raw JSON. The CLIENT
                    # recognizes this exception type (via the WS error_type tag) and shows a clean
                    # "Vision Not Available" card instead of retrying 60 times for nothing.
                if _looks_like_mmproj_error(err_text):
                    logger.error(
                        f"[VISION] llama.cpp rejected image input: no multimodal projector (mmproj) "
                        f"is loaded for model '{model}'. Raw body: {err_text[:300]}"
                    )
                    raise make_vision_error(model) from None
                if "parse tool call arguments" in err_text.lower():
                    # The model's own tool-call JSON was cut off before it could be parsed.
                    # Usual causes (in order of likelihood): max_tokens hit mid-JSON,
                    # or a prompt so large that output room ran out. est_prompt_tokens
                    # now includes tool_calls args, so [CONTEXT-GUARD] logs are trustworthy.
                    logger.error(
                        f"[TOOL-JSON-PARSE] llama.cpp could not parse its own (truncated) tool-call JSON. "
                        f"Prompt ~{est_prompt_tokens} est tokens of the {CONTEXT_WINDOW_TOKENS}-token window; "
                        f"check [CONTEXT-GUARD]/[SAFE_TRIM] logs on the client side."
                    )
                    logger.error(f"[TOOL-JSON-PARSE] Raw llama.cpp error body: {err_text[:2000]}")
                    # Propagate a SHORT actionable message only. The raw body can be ~10KB of
                    # truncated JSON; sending it to the client would poison logs and history.
                    raise RuntimeError(
                        "llama.cpp truncated its own tool-call JSON (context exhausted mid-output). "
                        f"Prompt ~{est_prompt_tokens} tokens left only {max(0, CONTEXT_WINDOW_TOKENS - est_prompt_tokens)} of {CONTEXT_WINDOW_TOKENS}. "
                        "Re-issue with smaller payloads (split large code into multiple calls)."
                    )
                logger.error(f"llama.cpp HTTP 500 body: {err_text[:2000]}")
                raise RuntimeError(f"llama.cpp server error: {err_text.strip()[:300]}")
            elif response.status_code == 400:
                    # Read the actual error body from llama.cpp for debugging
                    error_body = (await response.aread()).decode("utf-8", errors="replace")
                    logger.error(f"llama.cpp HTTP 400 Bad Request - body: {error_body[:500]}")
                    raise RuntimeError(f"llama.cpp returned HTTP 400: {error_body.strip()[:300]}")
            elif response.status_code != 200:
                error_text = await response.aread()
                raise RuntimeError(f"llama.cpp returned HTTP {response.status_code}")

            # Effective stall timeout scales with prompt size so a legitimate
            # long prefill of a near-full context is not mistaken for a freeze.
            effective_stall = max(
                LLAMA_STREAM_STALL_TIMEOUT_SEC,
                min(600, est_prompt_tokens // 400),
            )
            logger.info(f"[STREAM] Stall watchdog armed: {effective_stall}s (est_prompt={est_prompt_tokens} tokens)")

            async for line in _iter_sse_with_stall(response.aiter_lines(), effective_stall, conv_id or "", api_url):
                # ---- STOP CHECK: on every SSE chunk ----
                if stop_event and stop_event.is_set():
                    was_stopped = True
                    logger.info(f"Stop requested for conversation {conv_id}, ending generation")
                    await flush_content()
                    await flush_thinking()
                    break

                if not line.strip():
                    continue

                if not line.startswith("data:"):
                    continue

                data_str = line[5:].strip()
                if data_str == "[DONE]":
                    break

                try:
                    data = json.loads(data_str)

                    # ============================================================
                    # CRITICAL FIX: Capture token stats from the 'usage' field
                    # Present in final chunks of llama.cpp responses
                    # ============================================================
                    usage = data.get("usage", {})
                    if usage:
                        if "prompt_tokens" in usage:
                            prompt_tokens = usage.get("prompt_tokens", 0)
                        if "completion_tokens" in usage:
                            completion_tokens = usage.get("completion_tokens", 0)
                        # eval_duration in nanoseconds - convert to seconds
                        eval_dur_ns = usage.get("eval_duration", 0)
                        if eval_dur_ns:
                            eval_duration_seconds = eval_dur_ns / 1_000_000_000

                        logger.info(
                            f"[Llama.cpp] Token stats - prompt: {prompt_tokens}, "
                            f"completion: {completion_tokens}, "
                            f"duration: {eval_duration_seconds:.2f}s"
                        )

                    choices = data.get("choices", [])
                    if choices:
                        # TRUNCATION FIX (2026-09-10): llama.cpp reports finish_reason on the final chunk
                        # ("stop" = natural end, "length" = hit max_tokens). The old code dropped it
                        # entirely, so a cut-off answer looked like a complete one and the ReAct loop
                        # re-asked forever. Capture every value seen; the last non-null wins.
                        fr = choices[0].get("finish_reason")
                        if fr:
                            finish_reason = fr
                        delta = choices[0].get("delta", {})

                        # Tool calls - accumulate deltas
                        if "tool_calls" in delta and delta["tool_calls"]:
                            for tc_delta in delta["tool_calls"]:
                                tc_index = tc_delta.get("index", 0)
                                while len(accumulated_tool_calls) <= tc_index:
                                    accumulated_tool_calls.append({
                                        "id": "",
                                        "type": "function",
                                        "function": {"name": "", "arguments": ""}
                                    })
                                acc_tc = accumulated_tool_calls[tc_index]
                                if tc_delta.get("id"):
                                    acc_tc["id"] = tc_delta["id"]
                                if tc_delta.get("type"):
                                    acc_tc["type"] = tc_delta["type"]
                                func = tc_delta.get("function", {})
                                if func.get("name"):
                                    acc_tc["function"]["name"] = func["name"]
                                if func.get("arguments"):
                                    acc_tc["function"]["arguments"] += func["arguments"]

                        # ---- Thinking / Reasoning content extraction ----
                        think_chunk = None
                        if enable_thinking:
                            think_chunk = delta.get("reasoning_content", "")

                        if think_chunk:
                            think_buffer += think_chunk
                            await flush_thinking()

                        # Content chunk
                        chunk = delta.get("content", "")
                        if chunk:
                            full_response_parts.append(chunk)
                            content_buffer += chunk
                            message_counter += 1

                            current_time = asyncio.get_running_loop().time()
                            should_flush = (
                                len(content_buffer) >= STREAM_BUFFER_SIZE_CHARS or
                                message_counter >= STREAM_BUFFER_SIZE_MSGS or
                                (current_time - last_send_time) >= STREAM_BUFFER_TIMEOUT_SEC
                            )

                            if should_flush:
                                await flush_content()

                except json.JSONDecodeError:
                    logger.warning(f"Failed to parse SSE line: {line[:100]}")
                    continue

            # Final flush (skip if stopped - already flushed on break)
            if not was_stopped:
                await flush_content()
                await flush_thinking()

            # Return accumulated tool calls if any
            if accumulated_tool_calls:
                logger.info(f"Received {len(accumulated_tool_calls)} native tool call(s)")

            full_response = ''.join(full_response_parts)
            total_duration = time.time() - start_time

            # ============================================================
            # Calculate generation speed from REAL llama.cpp data
            # ============================================================
            gen_speed = None
            if eval_duration_seconds > 0 and completion_tokens > 0:
                gen_speed = round(completion_tokens / eval_duration_seconds, 1)
                logger.info(
                    f"Generation speed: {gen_speed} tok/s "
                    f"({completion_tokens} tokens in {eval_duration_seconds:.2f}s)"
                )
            elif total_duration > 0 and completion_tokens > 0:
                # Fallback using total request time
                gen_speed = round(completion_tokens / total_duration, 1)
                logger.info(f"Fallback speed estimate: {gen_speed} tok/s (using total duration)")

            # If we never saw token stats, log a warning
            if prompt_tokens == 0 and completion_tokens == 0:
                logger.warning(
                    f"No token statistics received from llama.cpp! "
                    f"Response length: {len(full_response)} chars"
                )
                # Try to estimate tokens roughly (fallback)
                prompt_tokens = max(1, sum(len(str(m.get("content", ""))) // 4 for m in messages))
                completion_tokens = max(1, len(full_response) // 4)

            # TRUNCATION FIX (2026-09-10): expose finish_reason to the client. "length" with no
            # tool call means the answer was CUT OFF at max_tokens - the ReAct loop must treat it
            # differently from a normal thinking step (resume/accept) instead of re-asking forever.
            was_truncated = bool(finish_reason == "length" and not accumulated_tool_calls)
            if finish_reason:
                logger.info(
                    f"[Llama.cpp] finish_reason={finish_reason!r} (truncated={was_truncated}, "
                    f"completion_tokens={completion_tokens})"
                )
            if was_truncated:
                logger.warning(
                    f"[TRUNCATED] Generation hit the output limit ({safe_max_tokens} tokens) before finishing. "
                    f"The client will resume or accept this partial answer instead of looping."
                )

            # Build the TokenStats with REAL data from llama.cpp
            stats = TokenStats(
                prompt_tokens=prompt_tokens,
                generated_tokens=completion_tokens,
                truncated=was_truncated,
                generation_speed=gen_speed,
                total_duration=round(total_duration, 2),
                provider_name="llama",
                model=model,
                context_window=CONTEXT_WINDOW_TOKENS,
            )

            logger.info(
                f"[Llama.cpp] Final TokenStats: prompt={stats.prompt_tokens}, "
                f"gen={stats.generated_tokens}, speed={stats.generation_speed}, "
                f"remaining={stats.tokens_remaining}"
            )

            if accumulated_tool_calls:
                return json.dumps({
                    "type": "tool_calls",
                    "tool_calls": accumulated_tool_calls
                }), stats

            return full_response, stats

    except httpx.ConnectError as e:
        logger.error(f"Cannot connect to llama.cpp: {e}")
        raise ConnectionError("llama.cpp service is not running. Please start llama-server.")
    except httpx.TimeoutException as e:
        logger.error(f"llama.cpp timeout after {timeout}s: {e}")
        raise TimeoutError(f"llama.cpp request timed out after {timeout} seconds.")
    except VisionNotAvailableError as e:
        # Expected user-facing condition (image sent to a model without mmproj), NOT a
        # server fault — log one clean line, no traceback. The typed error still propagates
        # so chat_relay can tag the WS frame and show the "Vision Not Available" card.
        logger.warning(f"[VISION] Image input rejected for model '{model}': {e}")
        raise
    except Exception as e:
        logger.error(f"llama.cpp stream failed: {e}")
        raise
