"""
ReAct (Reasoning + Acting) loop control for agentic mode.


Handles:
- Main tool iteration loop with provider-native tool calling
- Token stats pushing after every provider call
- Tool result processing and message history management
- Stop event checking between iterations
- Safe-margin token warning + context-guardian finish/plan message before hard trim
- Temp thinking array to preserve all AI reasoning steps in final history

FIXED (2026-01-XX): Restored loop exit logic from working version.
FIXED (2026-01-XX): ToolCompilationError now terminates loop immediately without retry.
"""


import json
import logging
import re
import time
from typing import List, Dict, Any, Tuple

from config import (
    AGENTIC_MAX_TOOL_ITERATIONS,
    AGENTIC_MAX_THINKING_ITERATIONS,
    AGENTIC_TOKEN_WARNING_THRESHOLD,
    AGENTIC_MAX_CONTEXT_GUARDIAN_INJECTIONS,
)




from utils.history_manager import (
    max_history_tokens,
    invalidate_message_tokens,
    estimate_message_tokens,
)
from utils.history_trimmer import safe_trim_history, get_token_count

# ============================================================
# LEARNED LESSONS - DISABLED ON PURPOSE (dead code kept on purpose).
# Will be fixed later: we are coming back to this. For now the whole lessons
# pipeline is skipped so it neither inflates the system prompt nor complicates
# history trimming. The old logic stays in place as dead code below - re-enable
# by setting _LESSONS_INJECTION_ENABLED = True.
# ============================================================
_LESSONS_INJECTION_ENABLED = False


from .base_mode import push_token_stats, check_stop_event, build_session_stats
from .provider_call import call_provider_with_retry
from .tool_lock import tool_lock, SCREEN_BROWSER_TOOLS


logger = logging.getLogger("COOLEMS.Logic.ReactLoop")


# Lazy-import ToolCompilationError to avoid circular dependency at module load time
def _get_tool_compilation_error():
    """Get the ToolCompilationError class (lazy import)."""
    try:
        from tools.remote_tools.dynamic_loader import ToolCompilationError
        return ToolCompilationError
    except ImportError:
        # Fallback for when running in CLIENT context where module path differs
        try:
            from CLIENT.tools.remote_tools.dynamic_loader import ToolCompilationError
            return ToolCompilationError
        except ImportError:
            return None


async def run_react_loop(
    config: Any,
    messages: List[Dict],
    tool_executor: Any,
    conversation_history: List[Dict],
) -> str:
    """
    Run the ReAct loop for agentic mode.

    Args:
        config: AgenticModeConfig with provider, websocket, etc.
        messages: Initial messages list (system + history + user).
        tool_executor: ToolExecutor instance for tool execution.
        conversation_history: Original full conversation history.

    Returns:
        Final AI response string (includes all accumulated thinking steps).

    HISTORY TRIMMING CONTRACT (atomic units):
        - messages[0] (system prompt) is NEVER removed.
        - The CURRENT USER PROMPT (tagged `_protect` by build_messages) is NEVER
          removed - it must remain in the list at all times.
        - Everything else is grouped into atomic units (a turn = user msg + the AI
          reply that answered it + ALL its tool results) and only whole units are
          ever removed, oldest first. An assistant message with `tool_calls` can
          therefore never be separated from its tool results.
        - There is NO minimum-message floor: if the budget requires it, every
          removable unit goes and only [system prompt + current user prompt]
          remain. Per-message token counts are cached on the dicts by
          estimate_message_tokens(), so trimming is a cheap sum of ints.
    """
    func_start = time.time()


    final_response = ""
    ai_response = ""
    tool_iteration = 0

    # LEARNED LESSONS - skipped on purpose (see _LESSONS_INJECTION_ENABLED at
    # module top). Kept as dead code: will be fixed later, we'll come back.
    agent_lessons = "" if not _LESSONS_INJECTION_ENABLED else None


    # TEMP THINKING ARRAY - accumulates AI reasoning responses between tool calls
    # When TASK DONE is encountered, ALL thinking steps are saved to history together
    temp_thinking: List[str] = []


    # CONSECUTIVE THINKING COUNTER - tracks thinking-only iterations without tool use
    consecutive_thinking_count = 0

    # REACT LOOP STATS - for UI display
    loop_tools = 0         # Total loop calls in this agentic run
    loop_no_tools = 0         # Non-tool calls since last tool call

    # (2026-08-23 session stats) TOTAL tokens generated by the provider across ALL loops of
    # this agentic run (loop 1 -> current). Pushed to the UI with every token_stats frame so
    # the status bar can show cumulative output for the whole session, not just one call.
    session_generated_tokens = 0

    # LAST PROVIDER STATS of this run - kept so the FINAL turn-stats line (spliced above
    # 'Agentic AI: TASK DONE' in the answer + sent as a 'turn_stats' frame) can show exactly
    # the numbers the UI status bar showed live during the loop.
    last_stats = None

    # CONTEXT-RECOVERY BUDGET - how many times this run may recover from a
    # truncated tool-call JSON (server error marker: "truncated its own tool-call").
    # Each recovery aggressively re-trims history and tells the model to use
    # smaller payloads. Bounded so a pathological prompt cannot loop forever.
    context_recoveries = 0
    MAX_CONTEXT_RECOVERIES = 3

    # TRUNCATION-RESUME BUDGET (2026-09-10): how many times this run may ask the model to
    # resume a response that was cut off at the output token limit (finish_reason == "length").
    # Before this fix a truncated answer looked like an ordinary thinking step, so the loop
    # hit max-thinking-iterations, injected 'end with TASK DONE' and re-asked from scratch -
    # forever (see plan_20260910_1835.md). After the budget is spent we accept the best
    # partial answer instead of looping.
    truncation_resumes = 0
    MAX_TRUNCATION_RESUMES = 2

    # CONTEXT-GUARDIAN BUDGET - how many times this run may inject the near-limit
    # guardian message (fires at AGENTIC_TOKEN_WARNING_THRESHOLD of token_limit).
    # The AI is told to finish its current work step and dump everything into a plan
    # file so the next work loop can pick up where this one left off.
    token_warning_sent = False  # console warning fires once per run at the safe-margin threshold
    context_guardian_injections = 0

    # SERVER-TRUTH TOKEN ANCHOR (2026-08-19 fix): after each provider call we remember the
    # REAL prompt_tokens reported by llama.cpp via the server's token_stats frame. That is
    # the authoritative "how much of the context window does the CURRENT message list cost"
    # number - it includes system + history + tool schema exactly as sent. The client-side
    # chars/4 estimate (get_token_count) can overcount by 10-30x on large payloads, which is
    # what made the guardian fire at "1061%" while the server showed ~33% used and then wiped
    # 90+ healthy messages. We trust the server number once we have one; the local estimate
    # is only a fallback for iterations before any response has come back yet.
    server_prompt_tokens = None      # real prompt_tokens from last provider call (None until first)
    messages_len_at_last_stats = 0   # len(messages) when we last received stats — tracks which msgs are "new"
    est_drift_logged = False         # log the local-vs-server estimate divergence once per run

    token_limit = max_history_tokens()

    # Output room is guaranteed SERVER-side now: streaming.py clamps
    # max_tokens to (context window - real prompt estimate), so llama.cpp can
    # never run out of room mid tool-call JSON. The client's only job here is
    # keeping the whole message list under token_limit via atomic-unit trim.

    # Tool schema is sent to the model EVERY request but get_token_count() does not
    # count it. Include it in the trim math so we stop drifting past the real window.
    _tools_for_est = getattr(config, "ollama_tools", None) or []
    est_tools_tokens = sum(len(json.dumps(t)) for t in _tools_for_est) // 4 if _tools_for_est else 0


    try:
        while tool_iteration < AGENTIC_MAX_TOOL_ITERATIONS:
            iteration_start = time.time()
            logger.info("-" * 50)


            # Check for stop signal at START of each iteration
            stopped = check_stop_event(config)
            if stopped:
                logger.warning("[AGENTIC.DEBUG] react_loop - STOP EVENT DETECTED, breaking loop")
                final_response = stopped
                if config.websocket:
                    await config.websocket.send_text(json.dumps({
                        "type": "system",
                        "content": "Generation stopped. Type new message to continue."
                    }))
                break




            # Increment total loop call counter
            loop_tools += 1
            # TOKEN BUDGET CHAIN (checked EVERY iteration, in this order):
            #   1. WARNING  - console warning when usage reaches the safe-margin
            #      percentage (AGENTIC_TOKEN_WARNING_THRESHOLD of token_limit).
            #   2. GUARDIAN - at that same threshold, inject a [SYSTEM NOTICE]
            #      telling the AI to finish its current work and write a plan file
            #      so we can continue in the next work loop (same pattern as the
            #      max-thinking-iterations force-completion guardian).
            #   3. TRIM     - when the budget is actually exceeded, remove oldest
            #      atomic units from the list sent to the provider.
            # SERVER-TRUTH ANCHOR (2026-08-19 fix): prefer the REAL prompt token count
            # llama.cpp reported for the last request we sent. The message list only grows
            # between iterations, so "server prompt_tokens + local estimate delta since that
            # call" is a faithful current-usage figure - and it already includes the tool
            # schema (the server counts exactly what was sent), which is why est_tools_tokens
            # must NOT be added on top of it. The local chars/4 estimate stays only as a
            # fallback for iterations before any response has come back yet, and drift from
            # the server number is logged once so estimator problems remain diagnosable.
            if server_prompt_tokens is not None:
                _new_msgs = messages[messages_len_at_last_stats:]
                current_tokens = server_prompt_tokens + sum(estimate_message_tokens(m) for m in _new_msgs)
                local_est_now = get_token_count(messages) + est_tools_tokens
                if not est_drift_logged and abs(local_est_now - current_tokens) > 5000:
                    est_drift_logged = True
                    logger.warning(
                        f"[AGENTIC.DEBUG] react_loop - TOKEN ESTIMATE DRIFT: local chars/4 estimate "
                        f"{local_est_now} vs server-truth {current_tokens} tokens. Budget decisions use the "
                        f"server number (authoritative) - this is why spurious 1061% guardian warnings are gone."
                    )
            else:
                current_tokens = get_token_count(messages) + est_tools_tokens

            # ---- STAGE 1+2: safe-margin warning + context guardian (95%) ----
            if current_tokens >= int(token_limit * AGENTIC_TOKEN_WARNING_THRESHOLD):
                pct = round(100.0 * current_tokens / token_limit) if token_limit else 0

                # Console warning - once per run, the moment we cross the threshold.
                if not token_warning_sent:
                    token_warning_sent = True
                    logger.warning(
                        f"[AGENTIC.DEBUG] react_loop - TOKEN SAFE-MARGIN WARNING: {current_tokens}/{token_limit} "
                        f"tokens ({pct}% of safe budget, threshold {round(100*AGENTIC_TOKEN_WARNING_THRESHOLD)}%). "
                        f"Trimming will engage as soon as the limit is exceeded."
                    )
                    if config.websocket:
                        await config.websocket.send_text(json.dumps({
                            "type": "system",
                            "content": (f"Context window at {pct}% of the safe token budget. "
                                        f"History will be trimmed automatically if it grows further.")
                        }))

                # Context guardian - same pattern as the max-thinking-iterations
                # force-completion message: tell the AI to wrap up and leave a plan.
                if context_guardian_injections < AGENTIC_MAX_CONTEXT_GUARDIAN_INJECTIONS:
                    context_guardian_injections += 1
                    logger.warning(
                        f"[AGENTIC.DEBUG] react_loop - CONTEXT GUARDIAN {context_guardian_injections}/{AGENTIC_MAX_CONTEXT_GUARDIAN_INJECTIONS}: "
                        f"{current_tokens}/{token_limit} tokens ({pct}%). Injecting finish-current-work + plan message."
                    )
                    context_guardian_msg = {
                        "role": "user",
                        "content": (
                            f"[SYSTEM NOTICE] The context window is at {pct}% of its safe token budget. "
                            "You MUST now finish the current work step and STOP calling tools. "
                            "Write a plan file (plan_<YYYYMMDD_HHMM>_continue.md in the working folder) that captures: "
                            "(1) what is already DONE, (2) the exact remaining steps to finish the task, and "
                            "(3) any context/decisions needed to continue in the next work loop. "
                            "Then end your response with 'Agentic AI: TASK DONE' so we can resume from that plan later."
                        )
                    }
                    messages.append(context_guardian_msg)
                    # Trim right away too - the guardian message itself costs tokens and
                    # we want maximum room left for the AI's wrap-up + plan file.
                    live_protected = [0]
                    for _pi in range(len(messages) - 1, -1, -1):
                        if messages[_pi].get("role") == "user":
                            live_protected.append(_pi)
                            break
                    messages = safe_trim_history(messages, max(1024, token_limit - est_tools_tokens), live_protected)

            # ---- STAGE 3: hard limit exceeded -> trim oldest atomic units ----
            if current_tokens > token_limit:
                logger.warning(f"[AGENTIC.DEBUG] react_loop - TOKEN LIMIT EXCEEDED! Trimming history...")
                # Recompute protected indices live on every trim: each previous trim rebuilt
                # `messages`, so any index computed earlier is stale after the first removal.
                # The `_protect` tag on the current user prompt is the primary guard;
                # this keeps index-based protection correct for repeated trims within one run.
                live_protected = [0]
                for _pi in range(len(messages) - 1, -1, -1):
                    if messages[_pi].get("role") == "user":
                        live_protected.append(_pi)
                        break
                # Trim budget for the MESSAGE LIST ONLY: subtract the tool-schema cost so
                # (messages + tools) actually fits under token_limit. The old code passed
                # token_limit itself, leaving messages ~est_tools_tokens over budget - the
                # real prompt then hit the window with almost no output room left and
                # llama.cpp truncated its own tool-call JSON mid-string ("Failed to parse
                # tool call arguments" 500). See plan_20260817_trace_fix.md.
                messages = safe_trim_history(messages, max(1024, token_limit - est_tools_tokens), live_protected)
                after_trim_tokens = get_token_count(messages) + est_tools_tokens
                logger.debug(f"[AGENTIC.DEBUG] react_loop - After trim: {len(messages)} messages, {after_trim_tokens} tokens (incl. tool schema)")


            # LEARNED LESSONS - injection skipped on purpose (dead code kept for a
            # later fix; see _LESSONS_INJECTION_ENABLED at module top). The block
            # below stays exactly as it was so we can re-enable by flipping the flag.
            updated_messages = messages
            if agent_lessons and _LESSONS_INJECTION_ENABLED:
                logger.debug("[AGENTIC.DEBUG] react_loop - Injecting agent lessons into system prompt")
                for msg in updated_messages:
                    if msg["role"] == "system":
                        msg["content"] = f"""{msg["content"]}


{agent_lessons}"""
                        break

            # Provider call with automatic restart on connection error.
            # Bounded recovery: if the SERVER reports its own tool-call JSON was truncated
            # (marker: "truncated its own tool-call"), re-trim history aggressively and tell
            # the model to split payloads - instead of letting one context exhaustion kill
            # a multi-hour agentic run. The trim-budget fix above makes this rare; this is
            # the safety net for when it still happens (e.g. protected messages alone are huge).
            try:
                provider_result, stats = await call_provider_with_retry(config, updated_messages)


            except RuntimeError as _prov_err:
                if "truncated its own tool-call" in str(_prov_err) and context_recoveries < MAX_CONTEXT_RECOVERIES:
                    context_recoveries += 1
                    logger.warning(
                        f"[AGENTIC.DEBUG] react_loop - CONTEXT RECOVERY {context_recoveries}/{MAX_CONTEXT_RECOVERIES}: "
                        f"server truncated its own tool-call JSON. Aggressively re-trimming history..."                    )
                    live_protected = [0]
                    for _pi in range(len(messages) - 1, -1, -1):
                        if messages[_pi].get("role") == "user":
                            live_protected.append(_pi)
                            break
                    aggressive_limit = max(1024, int(token_limit * 0.75) - est_tools_tokens)
                    messages = safe_trim_history(messages, aggressive_limit, live_protected)
                    recovery_notice = {"role": "user", "content": (
                        "[SYSTEM NOTICE] Your previous tool call was truncated because the context window ran out. "
                        "Continue the task with SMALLER payloads: split large code into multiple small calls "
                        "(one file per call, < ~200 lines each) and avoid re-sending content you already have.")
                    }
                    messages.append(recovery_notice)
                    continue
                raise
            except Exception as _cancel_err:
                # CANCEL FIX (2026-09-07): the user clicked Stop WHILE this provider call was
                # streaming. direct_mode/relay_mode raise UserCancelled in that case (matched by
                # class name - it is defined per module and crosses the retry boundary as a plain
                # exception). Treat it exactly like the loop-start stop check: no error log, no
                # re-raise, just break with the clean "stopped" result. Before this fix the
                # exception fell into the generic handler below ("UNEXPECTED ERROR") and bubbled
                # up as a provider failure even though it was a deliberate user cancel.
                if type(_cancel_err).__name__ == "UserCancelled":
                    logger.warning("[AGENTIC.DEBUG] react_loop - UserCancelled raised by provider mid-stream; stopping cleanly without executing further tools")
                    final_response = "Generation stopped by user."
                    if config.websocket:
                        try:
                            await config.websocket.send_text(json.dumps({
                                "type": "system",
                                "content": "Generation stopped. Type new message to continue."
                            }))
                        except Exception:
                            pass  # UI socket may already be closed after a stop click
                    break
                # Not a user cancel - this was a real error: re-raise so the normal
                # handlers below (truncated-tool-call recovery / generic error path) apply.
                raise _cancel_err


            # Push token stats to UI
            logger.debug("[AGENTIC.DEBUG] react_loop - Sending token stats to UI")
            if stats and getattr(stats, "generated_tokens", 0):
                session_generated_tokens += int(stats.generated_tokens or 0)
            _sess_stats = build_session_stats(config)   # active-time elapsed (pauses excluded) + last turn
            loop_stats = {
                "loop_tools": loop_tools,
                "loop_no_tools": loop_no_tools,
                # (2026-08-23 session stats) additive UI fields:
                "session_generated_tokens": session_generated_tokens,
                "session_elapsed_sec": _sess_stats["session_elapsed_sec"],
                "last_session_sec": _sess_stats["last_session_sec"],
            }
            await push_token_stats(config.websocket, stats, loop_stats)
            if stats is not None:
                last_stats = stats   # remember for the final turn-stats line at loop exit

            if stats:
                logger.info(
                    f"prompt={stats.prompt_tokens}, "
                    f"generated={stats.generated_tokens}, "
                    f"speed={stats.calculated_speed}, "
                    f"remaining={stats.tokens_remaining}"
                )

                # Refresh the SERVER-TRUTH anchor: this is the real cost of exactly the
                # message list we just sent (system + history + tool schema, as counted by
                # llama.cpp). We remember len(messages) at that moment so the next iteration
                # can slice messages[len_at_last:] and only estimate tokens for NEW messages.
                if stats.prompt_tokens and stats.prompt_tokens > 0:
                    server_prompt_tokens = int(stats.prompt_tokens)
                    messages_len_at_last_stats = len(messages)




            # Check for tool calls — FILTER OUT MALFORMED ONES (empty/whitespace names)
            raw_tool_calls = _extract_tool_calls(provider_result)
            tool_calls = [tc for tc in raw_tool_calls if _is_valid_tool_call(tc)]


            if tool_calls:

                # CANCEL FIX (2026-09-07): the stop event can be set WHILE the provider call was
                # in flight (user clicked Stop mid-stream). The response still arrives with tool
                # calls, but executing them after a cancel is exactly the "processes keep running"
                # bug. Check again right before execution: if we were cancelled, do NOT run any of
                # these tools - break out and report stop instead.
                stopped = check_stop_event(config)
                if stopped:
                    logger.warning("[AGENTIC.DEBUG] react_loop - STOP EVENT set during provider call; discarding %d pending tool call(s), not executing", len(tool_calls))
                    final_response = stopped
                    if config.websocket:
                        try:
                            await config.websocket.send_text(json.dumps({
                                "type": "system",
                                "content": "Generation stopped. Type new message to continue."
                            }))
                        except Exception:
                            pass  # UI socket may already be closed after a stop click
                    break

                # TOOL EXECUTION - clear temp thinking array (new action phase starts)
                logger.debug(f"[AGENTIC.DEBUG] react_loop - Tool execution detected, clearing {len(temp_thinking)} accumulated thinking step(s)")
                temp_thinking = []


                # Reset consecutive thinking counter on tool use
                consecutive_thinking_count = 0


                # Reset loop_no_tools counter on tool use (for UI stats)
                loop_no_tools = 0

                logger.debug(f"[AGENTIC.DEBUG] react_loop - Processing {len(tool_calls)} native tool call(s) (filtered from {len(raw_tool_calls)})")


                # Add assistant message with tool calls.
                # content must be None (not an empty string) - the standard OpenAI format for
                # pure tool-call messages; an empty string can confuse chat templates and is one
                # of the triggers for malformed follow-up output from llama.cpp.
                assistant_msg = {
                    "role": "assistant",
                    "content": None,
                    "tool_calls": tool_calls
                }
                messages.append(assistant_msg)


                # Execute each tool call and accumulate lessons.
                # CANCEL FIX (2026-09-07): re-check the stop event between individual tools of a
                # multi-tool batch so a cancel mid-batch stops the remaining ones too.
                for tc_idx, tc in enumerate(tool_calls):
                    if check_stop_event(config) is not None:
                        logger.warning("[AGENTIC.DEBUG] react_loop - STOP EVENT set mid-batch; skipping %d remaining tool call(s)", len(tool_calls) - tc_idx)
                        break
                    agent_lessons = await _execute_single_tool_call(
                        tc, tool_executor, config, messages,
                        conversation_history, agent_lessons
                    )


                tool_iteration += 1


                iteration_elapsed = time.time() - iteration_start
                continue
            else:
                # No tool calls - check if task is truly done
                ai_response = provider_result if isinstance(provider_result, str) else str(provider_result)

                if "Agentic AI: TASK DONE" in ai_response:
                    # TASK COMPLETE - build final response from ALL accumulated thinking + this last message
                    temp_thinking.append(ai_response)


                    if len(temp_thinking) > 1:
                        logger.info(f"[AGENTIC.DEBUG] react_loop - TASK DONE with {len(temp_thinking)} accumulated thinking step(s)")
                    else:
                        logger.debug("[AGENTIC.DEBUG] react_loop - TASK DONE (single response)")


                    # Concatenate all thinking steps into final_response for history preservation
                    separator = "\n\n" + "=" * 50 + "\n\n"
                    final_response = separator.join(temp_thinking)
                    break
                else:
                    # TRUNCATION FIX (2026-09-10): the server now reports finish_reason == "length" via
                    # stats.truncated. A cut-off answer must NOT be treated as a normal thinking step -
                    # that is what caused the infinite 'Max thinking iterations' re-ask loop.
                    if stats and getattr(stats, "truncated", False):
                        if truncation_resumes < MAX_TRUNCATION_RESUMES:
                            truncation_resumes += 1
                            logger.warning(
                                f"[AGENTIC.DEBUG] react_loop - TRUNCATED RESPONSE {truncation_resumes}/{MAX_TRUNCATION_RESUMES}: "
                                f"provider hit its output limit ({stats.generated_tokens} tokens) mid-answer. Asking for a resume."
                            )
                            if config.websocket:
                                try:
                                    await config.websocket.send_text(json.dumps({
                                        "type": "system",
                                        "content": ("Response was cut off at the output limit - "
                                                     f"asking the model to resume ({truncation_resumes}/{MAX_TRUNCATION_RESUMES})..."),
                                    }))
                                except Exception:
                                    pass  # UI socket may already be closed
                            # The model can only resume if it SEES what it already wrote - add the partial
                            # answer to the message list first (same merge rule as the normal thinking path).
                            if messages and messages[-1].get("role") == "assistant" and not messages[-1].get("tool_calls"):
                                messages[-1]["content"] = (messages[-1].get("content") or "") + "\n\n" + ai_response
                                invalidate_message_tokens(messages[-1])  # content mutated in place -> refresh cached token count
                            else:
                                messages.append({"role": "assistant", "content": ai_response})

                            resume_msg = {
                                "role": "user",
                                "content": (
                                    "[SYSTEM NOTICE] Your previous response was CUT OFF mid-sentence by the output token limit. "
                                    "Continue EXACTLY where you stopped - do NOT repeat or re-describe anything already written, "
                                    "and finish the answer now. End your response with 'Agentic AI: TASK DONE'."
                                ),
                            }
                            messages.append(resume_msg)

                            # Keep the partial in temp_thinking: at TASK DONE time final_response is built from
                            # ALL accumulated steps, so both halves of the split answer end up in history.
                            # (This does NOT count as a thinking iteration for the max-thinking counter.)
                            temp_thinking.append(ai_response)

                            tool_iteration += 1
                            continue
                        else:
                            # Resume budget spent: accept the best partial answer instead of looping forever.
                            logger.warning(
                                f"[AGENTIC.DEBUG] react_loop - TRUNCATION RESUME BUDGET SPENT ({MAX_TRUNCATION_RESUMES}): "
                                f"accepting partial answer as final instead of looping."
                            )
                            if config.websocket:
                                try:
                                    await config.websocket.send_text(json.dumps({
                                        "type": "system",
                                        "content": ("Model kept hitting the output limit - delivering the best partial answer. "
                                                     "The response may be incomplete."),
                                    }))
                                except Exception:
                                    pass
                            temp_thinking.append(ai_response)
                            separator = "\n\n" + "=" * 50 + "\n\n"
                            final_response = separator.join(temp_thinking) if len(temp_thinking) > 1 else ai_response
                            # Keep the history contract: final answers end with the TASK DONE marker.
                            if "Agentic AI: TASK DONE" not in final_response:
                                final_response += "\n\nAgentic AI: TASK DONE"
                            break

                    # Increment consecutive thinking counter
                    consecutive_thinking_count += 1


                    # Increment loop_no_tools counter (for UI stats)
                    loop_no_tools += 1
                    logger.debug(f"[AGENTIC.DEBUG] react_loop - Consecutive thinking count: {consecutive_thinking_count}")


                    # Check if we have exceeded max thinking iterations without tool use
                    if consecutive_thinking_count >= AGENTIC_MAX_THINKING_ITERATIONS:
                        logger.warning(
                            f"[AGENTIC.DEBUG] react_loop - Max thinking iterations ({AGENTIC_MAX_THINKING_ITERATIONS}) "
                            f"reached! Injecting completion message to AI."
                        )


                        # Send a message forcing the AI to complete with TASK DONE marker
                        force_completion_msg = {
                            "role": "user",
                            "content": (
                                "[SYSTEM NOTICE] You have exceeded the maximum number of consecutive thinking iterations. "
                                "You MUST now provide your final answer and end this agentic loop immediately. "
                                "Include 'Agentic AI: TASK DONE' at the very end of your response to signal completion."
                            )
                        }
                        messages.append(force_completion_msg)


                        # Reset counter so we do not keep injecting on next iteration
                        consecutive_thinking_count = 0


                        # Continue loop - let provider process the force message
                        tool_iteration += 1
                        continue


                    logger.debug("[AGENTIC.DEBUG] react_loop - No 'Agentic AI: TASK DONE' marker, accumulating thinking")


                    # Accumulate this thinking step in temp array
                    temp_thinking.append(ai_response)
                    logger.debug(f"[AGENTIC.DEBUG] react_loop - Thinking step {len(temp_thinking)} accumulated (total chars: {sum(len(t) for t in temp_thinking)})")


                    # Add to internal messages for context (merged with previous assistant if consecutive).
                    # None-safe: a pure tool-call assistant message carries content=None (OpenAI format),
                    # so `+=` would raise TypeError when one sits at messages[-1] - use the same
                    # `(content or "") + ...` merge rule as the truncation-resume path above.
                    if messages and messages[-1].get("role") == "assistant":
                        messages[-1]["content"] = (messages[-1].get("content") or "") + "\n\n" + ai_response
                        invalidate_message_tokens(messages[-1])  # content mutated in place -> refresh cached token count
                    else:
                        assistant_msg = {
                            "role": "assistant",
                            "content": ai_response
                        }
                        messages.append(assistant_msg)
                    tool_iteration += 1
                    continue


        # (2026-10-10) FINAL TURN STATS: splice the last loop-stats line directly above
        # "Agentic AI: TASK DONE" in the persisted answer AND send it as a "turn_stats"
        # frame so the live bubble gets the same line. The UI handler is idempotent, so
        # replayed frames and DB-loaded bubbles can never double-print it.
        if final_response and "Agentic AI: TASK DONE" in final_response:
            _elapsed_final = time.time() - func_start
            stats_line = _format_turn_stats_line(last_stats, loop_tools, loop_no_tools,
                                                 session_generated_tokens, _elapsed_final)
            if stats_line:
                # (2026-10-10 fix) Target ONLY the marker on its own line. The model can
                # mention "Agentic AI: TASK DONE" mid-prose ("...end with 'Agentic AI:
                # TASK DONE'") - splicing before such a meta-mention put the stats at the
                # TOP of the answer, which looked humanly wrong. The LAST standalone line
                # carrying the marker is the real end marker; if none exists (marker only
                # appears mid-line), append both lines cleanly at the very end instead.
                _m = None
                for _m in re.finditer(r"(?m)^[ \t]*Agentic AI: TASK DONE[ \t]*$", final_response):
                    pass  # loop ends with the LAST standalone match (or None)
                if _m is not None:
                    final_response = (final_response[:_m.start()] + stats_line + "\n"
                                      + final_response[_m.start():])
                else:
                    final_response = (final_response.rstrip("\n") + "\n" + stats_line
                                      + "\nAgentic AI: TASK DONE")
                logger.info(f"[AGENTIC.DEBUG] react_loop - Final turn stats: {stats_line}")
                if config.websocket:
                    try:
                        await config.websocket.send_text(json.dumps({
                            "type": "turn_stats",
                            "line": stats_line,
                        }))
                    except Exception:
                        pass  # UI socket may already be closed - the persisted answer still carries it

        # Loop exit - RESTORED to match working version
        if not final_response:
            logger.warning("[AGENTIC.DEBUG] react_loop - Loop exited but no final_response, using fallback")


            # If we have accumulated thinking but loop ended without TASK DONE marker, save it anyway
            if temp_thinking:
                separator = "\n\n" + "=" * 50 + "\n\n"
                final_response = separator.join(temp_thinking)
                logger.info(f"[AGENTIC.DEBUG] react_loop - Saving {len(temp_thinking)} thinking step(s) from incomplete loop")
            else:
                final_response = ai_response if ai_response else "I've completed the tasks."
                # Keep the history contract: final answers end with the TASK DONE marker
                # (the model may have been cut off before writing it).
                if "Agentic AI: TASK DONE" not in final_response:
                    final_response += "\n\nAgentic AI: TASK DONE"


        # Final token usage log
        final_tokens = get_token_count(messages)
        total_time = time.time() - func_start


        logger.info("=" * 60)
        logger.debug(f"[AGENTIC.DEBUG] react_loop - Final token count: {final_tokens} / {token_limit} ({len(messages)} messages)")
        logger.debug(f"[AGENTIC.DEBUG] react_loop - Total execution time: {total_time:.2f}s")
        logger.debug(f"[AGENTIC.DEBUG] react_loop - Final response length: {len(final_response)} chars")
        logger.debug(f"[AGENTIC.DEBUG] react_loop - EXIT")
        logger.info("=" * 60)


        return final_response


    except Exception as e:
        elapsed = time.time() - func_start
    
        # CRITICAL FIX: Check for ToolCompilationError BEFORE catching generic RuntimeError.
        # ToolCompilationError inherits from RuntimeError and was being caught by the 
        # (ConnectionError, TimeoutError, RuntimeError, FileNotFoundError) tuple below,
        # which caused it to be logged as "PROVIDER ERROR" - completely hiding the real
        # compilation failure and triggering useless retries.
        tool_comp_error = _get_tool_compilation_error()
        if tool_comp_error and isinstance(e, tool_comp_error):
            logger.error(
                f"[AGENTIC.DEBUG] react_loop - TOOL COMPILATION ERROR (non-retryable) "
                f"after {elapsed:.2f}s | iteration={tool_iteration}: {e}"
            )
        elif isinstance(e, (ConnectionError, TimeoutError)):
            logger.error(f"[AGENTIC.DEBUG] react_loop - PROVIDER ERROR after {elapsed:.2f}s | iteration={tool_iteration}")
        elif isinstance(e, FileNotFoundError):
            logger.error(f"[AGENTIC.DEBUG] react_loop - FILE NOT FOUND ERROR after {elapsed:.2f}s | iteration={tool_iteration}: {e}")
        else:
            logger.error(f"[AGENTIC.DEBUG] react_loop - UNEXPECTED ERROR ({type(e).__name__}) after {elapsed:.2f}s | iteration={tool_iteration}: {e}")


        # Even on error, log accumulated thinking if any
        if temp_thinking:
            logger.warning(f"[AGENTIC.DEBUG] react_loop - Error occurred with {len(temp_thinking)} thinking step(s) in buffer")


        raise


def _format_turn_stats_line(last_stats: Any, loop_tools: int, loop_no_tools: int,
                            session_generated_tokens: int, elapsed_sec: float) -> str:
    """Format the FINAL turn-stats line for an agentic run (2026-10-10).

    Renders EXACTLY like the UI status bar ("Loop stats: ... | 177K ctx | 9.3K sent |
    167.4K left | \u26a1 20.6 tok/s | \U0001F4DD 0.1K gen | \u23f1 0:08") so the user sees in the
    answer the same statistics that were live during the thinking process. Spliced directly
    above "Agentic AI: TASK DONE" and sent as a "turn_stats" frame for the live bubble.

    Returns "" when there is no provider stats object yet (nothing to report).
    """
    if last_stats is None:
        return ""
    try:
        window = int(getattr(last_stats, "context_window", 0) or 0)
        sent = int(getattr(last_stats, "prompt_tokens", 0) or 0)
        remaining = getattr(last_stats, "tokens_remaining", None)
        if remaining is None or remaining < 0:
            remaining = max(0, window - sent - (int(getattr(last_stats, "generated_tokens", 0) or 0)))
        speed = getattr(last_stats, "calculated_speed", None)
        if not speed and session_generated_tokens > 0 and elapsed_sec > 0:
            speed = session_generated_tokens / elapsed_sec   # honest fallback over the whole turn

        parts = [f"Loop stats: {loop_tools} / {loop_no_tools}",
                 f"{window // 1024}K ctx",
                 f"{sent / 1024:.1f}K sent",
                 f"{remaining / 1024:.1f}K left"]
        if speed and speed > 0:
            parts.append(f"\u26a1 {speed:.1f} tok/s")
        if session_generated_tokens > 0:
            parts.append(f"\U0001F4DD {session_generated_tokens / 1024:.1f}K gen")
        total = max(0.0, float(elapsed_sec or 0))
        h, rem = divmod(int(total), 3600)
        m, s = divmod(rem, 60)
        parts.append("\u23f1 " + (f"{h}:{m:02d}:" if h else f"{m}:") + f"{s:02d}")
        return " | ".join(parts)
    except Exception:
        logger.debug("[AGENTIC.DEBUG] turn-stats line formatting failed", exc_info=True)
        return ""


def _is_valid_tool_call(tc: Dict) -> bool:
    """Validate a tool call has a non-empty function name.
    
    Filters out malformed tool calls where the model returned empty/whitespace names.
    This prevents 'unknown' tool errors when the model hallucinates incomplete tool calls.
    
    Tool call structure from llama.cpp streaming:
        {
            "id": "call_xxx",
            "type": "function",
            "function": {"name": "tool_name", "arguments": "{}"}
        }
    """
    if not isinstance(tc, dict):
        return False
    
    func = tc.get("function")
    if not isinstance(func, dict):
        return False
    
    name = func.get("name", "")
    if not isinstance(name, str) or not name.strip():
        logger.warning(f"[AGENTIC.DEBUG] react_loop - Filtered out malformed tool call with empty/whitespace name: {tc}")
        return False
    
    return True


def _extract_tool_calls(result: Any) -> list:
    """Extract tool calls from provider result."""
    if isinstance(result, dict) and result.get("type") == "tool_calls":
        return result["tool_calls"]


    if isinstance(result, str):
        try:
            parsed = json.loads(result)
            if isinstance(parsed, dict) and parsed.get("type") == "tool_calls":
                return parsed["tool_calls"]
        except json.JSONDecodeError:
            logger.debug("[AGENTIC.DEBUG] react_loop - Response is plain text (not JSON), no tool calls")


    return []


def _repair_json_arguments(args_str):
        """Repair and parse malformed JSON from streamed tool call arguments.

        Only ONE safe completion is attempted: appending missing closing brackets
        when the payload is otherwise complete. A genuinely TRUNCATED payload (output
        token limit hit mid-string) or a corrupted one (raw newlines / stray quotes in
        values) is NEVER "repaired" - any dict salvaged from it would be partial data,
        and executing that (e.g. half-written python_exec code) is worse than failing loud.
        Returns parsed dict on success, None when the payload cannot be recovered
        safely (caller then feeds an actionable error back to the model).
        """
        if not args_str or not isinstance(args_str, str):
            return None

        # First try: parse as-is
        try:
            result = json.loads(args_str)
            if isinstance(result, dict):
                return result
        except (json.JSONDecodeError, TypeError):
            logger.debug("React loop: initial JSON parse failed for tool args, attempting repair")

        s = args_str.strip()

        # Safe completion: append the missing closing bracket when the payload is
        # otherwise complete (streaming occasionally drops only the final closer).
        for closing in ['}', ']', '{}', ']']:
            try:
                repaired = json.loads(s + closing)
                if isinstance(repaired, dict):
                    return repaired
            except (json.JSONDecodeError, TypeError):
                continue




        logger.error(f"[AGENTIC.DEBUG] react_loop - Could not repair JSON arguments (length={len(args_str)}): {args_str[:200]}")
        return None


async def _execute_single_tool_call(
    tc: Dict,
    tool_executor: Any,
    config: Any,
    messages: List[Dict],
    conversation_history: List[Dict],
    agent_lessons: str
) -> str:
    """Execute a single tool call and update messages with result.

    Tool call structure from llama.cpp streaming (OpenAI format):
        {
            "id": "call_xxx",
            "type": "function",
            "function": {"name": "tool_name", "arguments": "{}"}
        }

    Args:
        tc: Tool call dict from provider.
        tool_executor: ToolExecutor instance.
        config: AgenticModeConfig.
        messages: Current message list (modified in place).
        conversation_history: Full conversation history for context.
        agent_lessons: Existing lessons string to append to.

    Returns:
        Updated agent_lessons string.
    """
    # CRITICAL FIX: Tool call structure has name/arguments nested inside "function" key!
    func = tc.get("function", {}) if isinstance(tc, dict) else {}
    tool_name = func.get("name", "unknown") if isinstance(func, dict) else "unknown"
    tool_id = tc.get("id", "")


    # Parse arguments - handle both JSON strings and already-parsed dicts
    try:
        args_str = func.get("arguments", "{}") if isinstance(func, dict) else "{}"
        if isinstance(args_str, str):
            try:
                parsed_args = json.loads(args_str)
            except json.JSONDecodeError:
                logger.warning(f"[AGENTIC.DEBUG] react_loop - Malformed JSON in tool arguments for {tool_name}, attempting repair")
                parsed_args = _repair_json_arguments(args_str)
                if not parsed_args:
                    raise ValueError(f"Could not parse/repair tool arguments: {args_str[:200]}")
        else:
            parsed_args = args_str
    except Exception as e:
        logger.error(f"[AGENTIC.DEBUG] react_loop - Failed to parse arguments for {tool_name}: {e}")

        # Tell the model WHAT to do instead of echoing its own broken JSON back at it.
        # The usual cause is the output token limit cutting the tool-call JSON mid-string,
        # so the fix on the next iteration is a smaller payload, not a retry of the same one.
        error_msg = (
            f"Tool argument parsing failed for '{tool_name}': malformed or truncated JSON in tool arguments "
            '(likely hit the output token limit). Do NOT retry the same large payload - re-issue this'
            ' call with a SMALLER argument (e.g. split the code into multiple smaller python_exec calls)'
        )

        # Add tool result message with error
        tool_result_msg = {
            "role": "tool",
            "content": error_msg,
            "tool_call_id": tool_id
        }
        messages.append(tool_result_msg)
        return agent_lessons


    try:
        # FIX: Call tool_executor.execute() (the correct method name), NOT execute_tool().
        # ToolExecutor.execute() returns Tuple[str, str] = (tool_result, agent_lessons)
        # CRITICAL FIX (2026-08-27): pass live_messages=messages. Tool-viewed image
        # pixels (view_image / screenshots) are sanitized OUT of the tool-result text
        # before it is appended to history; ToolExecutor re-attaches them to the
        # PROTECTED current-user prompt so the NEXT provider call carries real pixels.
        # Without live_messages it fell back to `conversation_history` - a DIFFERENT
        # list than the one actually sent to the provider (build_messages copies
        # history[:-1] and creates a fresh protected user message). The re-attach
        # silently landed on a dict that is never sent -> the model only ever saw the
        # "[image: ... chars sanitized]" text reference and answered from imagination.
        # (2026-09-08 multi-chat) Screen/browser tools are serialized across chats:
        # two agentic loops must not fight over the same mouse/keyboard at once.
        _owner = getattr(config, 'conversation_id', None) or '_unknown'
        if tool_name in SCREEN_BROWSER_TOOLS:
            async with tool_lock(_owner):
                result_text, new_lessons = await tool_executor.execute(
                    tool_name=tool_name,
                    tool_args=parsed_args,
                    conversation_history=conversation_history,
                    websocket=config.websocket,
                    live_messages=messages,
                    conversation_id=getattr(config, 'conversation_id', None)  # python_exec approval gate (2026-09-24)
                )
        else:
            result_text, new_lessons = await tool_executor.execute(
                tool_name=tool_name,
                tool_args=parsed_args,
                conversation_history=conversation_history,
                websocket=config.websocket,
                live_messages=messages,
                conversation_id=getattr(config, 'conversation_id', None)  # python_exec approval gate (2026-09-24)
            )

        # Merge any new lessons from the tool execution
        if new_lessons:
            agent_lessons = (agent_lessons + "\n\n" + new_lessons).strip() if agent_lessons else new_lessons


        # Add tool result message
        tool_result_msg = {
            "role": "tool",
            "content": str(result_text),
            "tool_call_id": tool_id
        }
        messages.append(tool_result_msg)


    except Exception as e:
        logger.error(f"[AGENTIC.DEBUG] react_loop - Tool execution failed for {tool_name}: {e}")
        error_msg = f"Tool execution error: {str(e)[:500]}"
    
        # Add tool result message with error
        tool_result_msg = {
            "role": "tool",
            "content": error_msg,
            "tool_call_id": tool_id
        }
        messages.append(tool_result_msg)


    return agent_lessons
