"""
Token statistics data structures and WebSocket helpers.

Provides a unified TokenStats dataclass that captures real token counts
directly from the AI provider response (llama.cpp).

This module eliminates the old module-level global approach which was
broken for concurrent users. Instead, token stats are returned as part
of the chat_stream() return value and pushed to the UI via WebSocket.

Key Design Decisions:
    - TokenStats is a frozen dataclass (immutable after creation).
    - All fields have defaults so providers can fill what they have.
    - Speed is auto-calculated from tokens + duration when available.
    - A dedicated WebSocket message type 'token_stats' pushes data
      to the exact client that owns the conversation — zero data mixing
      between concurrent users.
"""

import logging
from dataclasses import dataclass
from typing import Optional

logger = logging.getLogger("COOLEMS.Provider.TokenStats")

@dataclass(frozen=True)
class TokenStats:
    """
    Immutable token statistics from a single AI provider call.

    Attributes:
        prompt_tokens: Number of tokens sent to the provider as input/context.
                       This is the ACTUAL count from the provider, not an estimate.
        generated_tokens: Number of tokens generated by the provider as output.
        generation_speed: Tokens per second for the generation phase.
                          Auto-calculated if not provided.
        total_duration: Total time in seconds for the entire request.
        truncated: True when the provider stopped generating because it hit the
                   output token limit (finish_reason == "length") with no tool call.
                   Lets the ReAct loop detect a cut-off answer instead of treating
                   it as a normal thinking step (2026-09-10 truncation-loop fix).
        provider_name: Which provider produced these stats ('llama').
        model: Model name used for this request.
        context_window: Total context window size in tokens for this model.
        tokens_remaining: Context window minus prompt_tokens minus generated_tokens.
                          Shows how much room is left in the context window.

    Calculation Notes:
        - If generation_speed is not provided but generated_tokens and
          generation_duration are available, it is auto-calculated.
        - tokens_remaining = context_window - prompt_tokens - generated_tokens
        - All values are non-negative; defaults to 0 if not available.
    """

    prompt_tokens: int = 0
    generated_tokens: int = 0
    truncated: bool = False
    generation_speed: Optional[float] = None
    total_duration: float = 0.0
    provider_name: str = ""
    model: str = ""
    context_window: int = 131072

    # Derived properties
    @property
    def tokens_remaining(self) -> int:
        """Tokens remaining in context window after this exchange."""
        return max(0, self.context_window - self.prompt_tokens - self.generated_tokens)

    @property
    def calculated_speed(self) -> Optional[float]:
        """Auto-calculated speed if not explicitly set."""
        if self.generation_speed is not None:
            return self.generation_speed
        if self.total_duration > 0 and self.generated_tokens > 0:
            return round(self.generated_tokens / self.total_duration, 1)
        return None

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization / WebSocket sending."""
        return {
            "prompt_tokens": self.prompt_tokens,
            "generated_tokens": self.generated_tokens,
            "truncated": self.truncated,
            "generation_speed": self.calculated_speed,
            "total_duration": round(self.total_duration, 2),
            "provider_name": self.provider_name,
            "model": self.model,
            "context_window": self.context_window,
            "tokens_remaining": self.tokens_remaining,
        }
